### ISSUE TITLE
Feature request of PTZ commands and preset positions in Axis cameras

### ISSUE THREAD

**Issue by jmfargas** [Kane610/axis#276] opened 2023-10-11 20:23 UTC
It would be nice to add PTZ commands and preset positions for Axis cameras. I tried the ONVIF integration and it sort of works, but it is extremely slow with the Axis cameras, so it's unusable.
In addition it would be nice to be able to force MJPEG video configuration, which is the fastest communication with the cameras.

**Comment by Kane610** [comment] 2023-10-12 20:04
Its on my todo, first I need to complete my rework of the library as its not a sustainable approach right now.

Duplicate of https://github.com/Kane610/axis/issues/229 so closing this.

**Closed by Kane610** 2023-10-12 20:04 UTC
